AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - ACM Certificate (us-east-1)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  RootDomainName:
    Type: String
  ApiDomainName:
    Type: String
  HostedZoneId:
    Type: String

Resources:

  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref RootDomainName
      SubjectAlternativeNames:
        - !Ref ApiDomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref RootDomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Ref ApiDomainName
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Application
          Value: !Ref AppName
        - Key: Environment
          Value: !Ref Env

Outputs:
  CertificateArn:
    Value: !Ref AcmCertificate
    Export:
      Name: !Sub '${AppName}-${Env}-AcmCertArnUsEast1'
