AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Billing Stack (Production Safe)

Parameters:
  AppName:
    Type: String
    Default: fusionems
  Env:
    Type: String
    AllowedValues: [dev, staging, prod]
  AppSecretsArn:
    Type: String
  LambdaSubnets:
    Type: String
  LambdaSecurityGroupId:
    Type: String
  ApiGatewayWebhookUrl:
    Type: String
  LambdaCodeS3Bucket:
    Type: String
  WorkersCodeS3Key:
    Type: String
    Default: workers/billing_workers.zip
  StripeProvisionerCodeS3Key:
    Type: String
    Default: stripe/webhook_provisioner.zip

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:

# ================= DynamoDB =================

  StripeEventsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub '${AppName}-${Env}-stripe-events'
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: !If [IsProd, true, false]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH

# ================= SQS =================

  StripeEventsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AppName}-${Env}-stripe-events-dlq.fifo'
      FifoQueue: true
      ContentBasedDeduplication: true
      KmsMasterKeyId: alias/aws/sqs

  StripeEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AppName}-${Env}-stripe-events.fifo'
      FifoQueue: true
      ContentBasedDeduplication: true
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 300
      KmsMasterKeyId: alias/aws/sqs
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt StripeEventsDLQ.Arn
        maxReceiveCount: 3

# ================= Worker Role =================

  WorkerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: WorkerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                Resource: !GetAtt StripeEventsTable.Arn
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !GetAtt StripeEventsQueue.Arn
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref AppSecretsArn

# ================= Stripe Worker =================

  StripeWorkerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: core_app.workers.stripe_worker.lambda_handler
      Role: !GetAtt WorkerLambdaRole.Arn
      Timeout: 120
      MemorySize: 512
      ReservedConcurrentExecutions: !If [IsProd, 50, 5]
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref WorkersCodeS3Key
      VpcConfig:
        SubnetIds: !Split [',', !Ref LambdaSubnets]
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
      Environment:
        Variables:
          STRIPE_EVENTS_TABLE: !Ref StripeEventsTable
          APP_SECRETS_ARN: !Ref AppSecretsArn
          ENV: !Ref Env

  StripeWorkerTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt StripeEventsQueue.Arn
      FunctionName: !GetAtt StripeWorkerFunction.Arn
      BatchSize: 10
      FunctionResponseTypes:
        - ReportBatchItemFailures

# ================= Stripe Provisioner =================

  StripeProvisionerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: StripeProvisionerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                Resource: "*"

  StripeWebhookProvisionerFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt StripeProvisionerRole.Arn
      Timeout: 60
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref StripeProvisionerCodeS3Key
      Environment:
        Variables:
          ENV: !Ref Env

  StripeWebhookEndpoint:
    Type: Custom::StripeWebhookEndpoint
    DependsOn: StripeWebhookProvisionerFunction
    Properties:
      ServiceToken: !GetAtt StripeWebhookProvisionerFunction.Arn
      AppSecretsArn: !Ref AppSecretsArn
      WebhookUrl: !Ref ApiGatewayWebhookUrl

Outputs:
  StripeEventsQueueUrl:
    Value: !Ref StripeEventsQueue

  StripeWorkerFunctionName:
    Value: !Ref StripeWorkerFunction
