AWSTemplateFormatVersion: '2010-09-09'
Description: >
  FusionEMS Quantum — Billing Integration Stack (Production Hardened)
  DynamoDB, SQS FIFO tuned, Lambda workers, Stripe webhook provisioner,
  full encryption, concurrency control, alarms.

Parameters:

  AppName:
    Type: String
    Default: fusionems

  Env:
    Type: String
    AllowedValues: [dev, staging, prod]

  AppSecretsArn:
    Type: String
    Description: ARN of secret containing stripe_secret_key, lob_api_key, etc.

  LambdaSubnets:
    Type: String
    Description: Comma-separated private subnet IDs

  LambdaSecurityGroupId:
    Type: String

  ApiGatewayWebhookUrl:
    Type: String
    Default: https://api.fusionemsquantum.com/webhooks/stripe

  LambdaCodeS3Bucket:
    Type: String

  WorkersCodeS3Key:
    Type: String
    Default: workers/billing_workers.zip

  StripeProvisionerCodeS3Key:
    Type: String
    Default: stripe/webhook_provisioner.zip

Conditions:
  IsProd: !Equals [!Ref Env, prod]

Resources:

# ─────────────────────────────────────────────────────────────
# DynamoDB
# ─────────────────────────────────────────────────────────────

  LobEventsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub '${AppName}-${Env}-lob-events'
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: !If [IsProd, true, false]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH

  StripeEventsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub '${AppName}-${Env}-stripe-events'
      BillingMode: PAY_PER_REQUEST
      DeletionProtectionEnabled: !If [IsProd, true, false]
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH

# ─────────────────────────────────────────────────────────────
# SQS FIFO (Tuned)
# ─────────────────────────────────────────────────────────────

  StripeEventsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AppName}-${Env}-stripe-events-dlq.fifo'
      FifoQueue: true
      MessageRetentionPeriod: 1209600
      KmsMasterKeyId: alias/aws/sqs

  StripeEventsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AppName}-${Env}-stripe-events.fifo'
      FifoQueue: true
      DeduplicationScope: messageGroup
      FifoThroughputLimit: perMessageGroupId
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 300
      KmsMasterKeyId: alias/aws/sqs
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt StripeEventsDLQ.Arn
        maxReceiveCount: 3

# ─────────────────────────────────────────────────────────────
# IAM Role
# ─────────────────────────────────────────────────────────────

  WorkerLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-${Env}-worker-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      Policies:
        - PolicyName: WorkerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - sqs:*
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref AppSecretsArn

# ─────────────────────────────────────────────────────────────
# Stripe Worker
# ─────────────────────────────────────────────────────────────

  StripeWorkerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AppName}-${Env}-stripe-worker'
      Runtime: python3.12
      Handler: core_app.workers.stripe_worker.lambda_handler
      Role: !GetAtt WorkerLambdaRole.Arn
      Timeout: 120
      MemorySize: 512
      ReservedConcurrentExecutions: 50
      TracingConfig:
        Mode: Active
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref WorkersCodeS3Key
      VpcConfig:
        SubnetIds: !Split [',', !Ref LambdaSubnets]
        SecurityGroupIds:
          - !Ref LambdaSecurityGroupId
      Environment:
        Variables:
          STRIPE_EVENTS_TABLE: !Ref StripeEventsTable
          APP_SECRETS_ARN: !Ref AppSecretsArn
          ENV: !Ref Env

  StripeWorkerTrigger:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt StripeEventsQueue.Arn
      FunctionName: !GetAtt StripeWorkerFunction.Arn
      BatchSize: 10
      FunctionResponseTypes:
        - ReportBatchItemFailures

# ─────────────────────────────────────────────────────────────
# Stripe Webhook Secret (Protected)
# ─────────────────────────────────────────────────────────────

  StripeWebhookSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: !Sub '${AppName}/${Env}/StripeWebhook'
      SecretString: '{"endpoint_id":"","signing_secret":""}'

# ─────────────────────────────────────────────────────────────
# Stripe Provisioner Lambda (S3 Packaged)
# ─────────────────────────────────────────────────────────────

  StripeProvisionerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StripeProvisionerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:PutSecretValue
                Resource:
                  - !Ref AppSecretsArn
                  - !Ref StripeWebhookSecret

  StripeWebhookProvisionerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AppName}-${Env}-stripe-webhook-provisioner'
      Runtime: python3.12
      Handler: index.handler
      Role: !GetAtt StripeProvisionerRole.Arn
      Timeout: 60
      Code:
        S3Bucket: !Ref LambdaCodeS3Bucket
        S3Key: !Ref StripeProvisionerCodeS3Key
      Environment:
        Variables:
          ENV: !Ref Env

  StripeWebhookEndpoint:
    Type: Custom::StripeWebhookEndpoint
    Properties:
      ServiceToken: !GetAtt StripeWebhookProvisionerFunction.Arn
      AppSecretsArn: !Ref AppSecretsArn
      WebhookUrl: !Ref ApiGatewayWebhookUrl
      WebhookSecretArn: !Ref StripeWebhookSecret

# ─────────────────────────────────────────────────────────────
# Alarms
# ─────────────────────────────────────────────────────────────

  StripeWorkerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-stripe-worker-errors'
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref StripeWorkerFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  StripeQueueAgeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-stripe-queue-age'
      Namespace: AWS/SQS
      MetricName: ApproximateAgeOfOldestMessage
      Dimensions:
        - Name: QueueName
          Value: !GetAtt StripeEventsQueue.QueueName
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 600
      ComparisonOperator: GreaterThanThreshold

Outputs:

  StripeEventsQueueUrl:
    Value: !Ref StripeEventsQueue

  StripeWebhookSecretArn:
    Value: !Ref StripeWebhookSecret

  StripeWorkerFunctionName:
    Value: !Ref StripeWorkerFunction
