AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Compute Stack (Production Safe ECS + ALB)

Parameters:
  AppName:
    Type: String
  Env:
    Type: String
  VpcId:
    Type: String
  PublicSubnets:
    Type: String
  PrivateSubnets:
    Type: String
  AlbSecurityGroupId:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String
  ImageTagFrontend:
    Type: String
  ImageTagBackend:
    Type: String
  DesiredCount:
    Type: Number
    Default: 0
    Description: >
      Set to 0 for the initial deploy (ECR images do not exist yet).
      The workflow updates services to 2 after pushing images.
  BackendContainerPort:
    Type: Number
    Default: 8000
  FrontendContainerPort:
    Type: Number
    Default: 3000
  AcmCertificateArn:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:

# ================= ECR =================

  BackendEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-backend'

  FrontendEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-frontend'

# ================= ECS =================

  EcsCluster:
    Type: AWS::ECS::Cluster

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

# ================= ALB =================

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: !Split [',', !Ref PublicSubnets]
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Scheme: internet-facing
      Type: application

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref BackendContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /api/v1/health

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref FrontendContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /healthz

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  BackendListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpsListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
            - /public/*
            - /ws/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

# ================= BACKEND =================

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: '1024'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-${Env}-backend:${ImageTagBackend}'
          PortMappings:
            - ContainerPort: !Ref BackendContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/${AppName}/${Env}/backend'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
              awslogs-create-group: 'true'

  BackendService:
    Type: AWS::ECS::Service
    DependsOn: BackendListenerRule
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref EcsServiceSecurityGroupId
          Subnets: !Split [',', !Ref PrivateSubnets]
      LoadBalancers:
        - TargetGroupArn: !Ref BackendTargetGroup
          ContainerName: backend
          ContainerPort: !Ref BackendContainerPort

# ================= FRONTEND =================

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-${Env}-frontend:${ImageTagFrontend}'
          PortMappings:
            - ContainerPort: !Ref FrontendContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/${AppName}/${Env}/frontend'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
              awslogs-create-group: 'true'

  FrontendService:
    Type: AWS::ECS::Service
    DependsOn: HttpsListener
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref FrontendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref EcsServiceSecurityGroupId
          Subnets: !Split [',', !Ref PrivateSubnets]
      LoadBalancers:
        - TargetGroupArn: !Ref FrontendTargetGroup
          ContainerName: frontend
          ContainerPort: !Ref FrontendContainerPort

Outputs:
  AlbDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  BackendEcrRepoUri:
    Value: !GetAtt BackendEcrRepository.RepositoryUri

  FrontendEcrRepoUri:
    Value: !GetAtt FrontendEcrRepository.RepositoryUri

  ClusterName:
    Value: !Ref EcsCluster

  BackendServiceName:
    Value: !Ref BackendService

  FrontendServiceName:
    Value: !Ref FrontendService

  BackendTaskDefinition:
    Value: !Ref BackendTaskDefinition
