AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Compute (ECR, ECS, ALB, backend/frontend/worker)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  VpcId:
    Type: String
  PublicSubnets:
    Type: String
  PrivateSubnets:
    Type: String
  AlbSecurityGroupId:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String
  ImageTag:
    Type: String
  DesiredCount:
    Type: Number
    Default: 2
  BackendContainerPort:
    Type: Number
    Default: 8000
  FrontendContainerPort:
    Type: Number
    Default: 3000
  DbSecretArn:
    Type: String
  AppSecretsArn:
    Type: String
  RedisEndpoint:
    Type: String
  CognitoUserPoolId:
    Type: String
  CognitoClientId:
    Type: String
  AlbCertificateArn:
    Type: String
  OpaImage:
    Type: String
    Default: openpolicyagent/opa:0.66.0
  OtelCollectorImage:
    Type: String
    Default: otel/opentelemetry-collector-contrib:0.105.0

Resources:
  BackendEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-backend'

  FrontendEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-frontend'

  WorkerEcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-worker'

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AppName}-${Env}-cluster'

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ReadRuntimeSecrets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource:
                  - !Ref DbSecretArn
                  - !Ref AppSecretsArn

  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}/app'
      RetentionInDays: 30

  Alb:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AppName}-${Env}-alb'
      Type: application
      Scheme: internet-facing
      SecurityGroups: [!Ref AlbSecurityGroupId]
      Subnets: !Split [',', !Ref PublicSubnets]
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '300'

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AlbCertificateArn
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '200'
            ContentType: text/plain
            MessageBody: 'listener-ready'

  HttpRedirectListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref Alb
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: '443'
            StatusCode: HTTP_301

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref BackendContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /api/v1/health
      Matcher:
        HttpCode: '200-399'

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref FrontendContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /healthz
      Matcher:
        HttpCode: '200-399'

  FrontendRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpsListener
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values: ['/*']
      Actions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  ApiRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpsListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values: ['/api/*', '/metrics', '/webhooks/*', '/public/*']
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-backend'
      RequiresCompatibilities: [FARGATE]
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Sub '${BackendEcrRepo.RepositoryUri}:${ImageTag}'
          PortMappings:
            - ContainerPort: !Ref BackendContainerPort
          Environment:
            - Name: REDIS_ENDPOINT
              Value: !Ref RedisEndpoint
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref CognitoUserPoolId
            - Name: COGNITO_CLIENT_ID
              Value: !Ref CognitoClientId
          Secrets:
            - Name: DATABASE_SECRET_ARN
              ValueFrom: !Ref DbSecretArn
            - Name: APP_SECRETS_ARN
              ValueFrom: !Ref AppSecretsArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: backend
        - Name: opa
          Image: !Ref OpaImage
          Command: ["run", "--server", "--addr=0.0.0.0:8181", "/policies"]
          PortMappings:
            - ContainerPort: 8181
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: opa
        - Name: otel-collector
          Image: !Ref OtelCollectorImage
          Essential: false
          PortMappings:
            - ContainerPort: 4318
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: otel

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-frontend'
      RequiresCompatibilities: [FARGATE]
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Sub '${FrontendEcrRepo.RepositoryUri}:${ImageTag}'
          PortMappings:
            - ContainerPort: !Ref FrontendContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: frontend

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-worker'
      RequiresCompatibilities: [FARGATE]
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt ExecutionRole.Arn
      ContainerDefinitions:
        - Name: worker
          Image: !Sub '${WorkerEcrRepo.RepositoryUri}:${ImageTag}'
          Secrets:
            - Name: DATABASE_SECRET_ARN
              ValueFrom: !Ref DbSecretArn
            - Name: APP_SECRETS_ARN
              ValueFrom: !Ref AppSecretsArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref AppLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: worker

  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${AppName}-${Env}-backend'
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EcsServiceSecurityGroupId]
          Subnets: !Split [',', !Ref PrivateSubnets]
      LoadBalancers:
        - TargetGroupArn: !Ref BackendTargetGroup
          ContainerName: backend
          ContainerPort: !Ref BackendContainerPort

  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${AppName}-${Env}-frontend'
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref FrontendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EcsServiceSecurityGroupId]
          Subnets: !Split [',', !Ref PrivateSubnets]
      LoadBalancers:
        - TargetGroupArn: !Ref FrontendTargetGroup
          ContainerName: frontend
          ContainerPort: !Ref FrontendContainerPort

  WorkerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${AppName}-${Env}-worker'
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref WorkerTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups: [!Ref EcsServiceSecurityGroupId]
          Subnets: !Split [',', !Ref PrivateSubnets]

Outputs:
  ClusterName:
    Value: !Ref EcsCluster
  BackendServiceName:
    Value: !GetAtt BackendService.Name
  FrontendServiceName:
    Value: !GetAtt FrontendService.Name
  WorkerServiceName:
    Value: !GetAtt WorkerService.Name
  AlbDnsName:
    Value: !GetAtt Alb.DNSName
  AlbFullName:
    Value: !GetAtt Alb.LoadBalancerFullName
  BackendTargetGroupFullName:
    Value: !GetAtt BackendTargetGroup.TargetGroupFullName
  BackendEcrRepoUri:
    Value: !GetAtt BackendEcrRepo.RepositoryUri
  FrontendEcrRepoUri:
    Value: !GetAtt FrontendEcrRepo.RepositoryUri
  WorkerEcrRepoUri:
    Value: !GetAtt WorkerEcrRepo.RepositoryUri
