AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Compute Stack (ECS Fargate multi-container + ALB + ECR)

Parameters:
  AppName:
    Type: String
  Env:
    Type: String
  VpcId:
    Type: String
  PublicSubnets:
    Type: String
  PrivateSubnets:
    Type: String
  AlbSecurityGroupId:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String
  ImageTagFrontend:
    Type: String
  ImageTagBackend:
    Type: String
  DesiredCount:
    Type: Number
    Default: 2
  BackendContainerPort:
    Type: Number
    Default: 8000
  FrontendContainerPort:
    Type: Number
    Default: 3000
  DbSecretArn:
    Type: String
  AppSecretsArn:
    Type: String
  RedisPrimaryEndpoint:
    Type: String
  CognitoUserPoolId:
    Type: String
  CognitoClientId:
    Type: String
  AcmCertificateArn:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, prod]

Resources:

  BackendEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-backend'

  FrontendEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-frontend'

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AppName}-${Env}-cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}/backend'
      RetentionInDays: !If [IsProd, 90, 30]

  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}/frontend'
      RetentionInDays: !If [IsProd, 90, 30]

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-${Env}-ecs-exec-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-${Env}-ecs-task-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AppName}-${Env}-alb'
      Subnets: !Split [',', !Ref PublicSubnets]
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Scheme: internet-facing
      Type: application
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '300'
        - Key: deletion_protection.enabled
          Value: !If [IsProd, 'true', 'false']

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AppName}-${Env}-backend-tg'
      Port: !Ref BackendContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /api/v1/health
      Matcher:
        HttpCode: '200-399'

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${AppName}-${Env}-frontend-tg'
      Port: !Ref FrontendContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /healthz
      Matcher:
        HttpCode: '200-399'

  HttpsListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AcmCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-backend'
      Cpu: '1024'
      Memory: '2048'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppName}-${Env}-backend:${ImageTagBackend}'
          PortMappings:
            - ContainerPort: !Ref BackendContainerPort
          HealthCheck:
            Command:
              - CMD-SHELL
              - !Sub 'curl -f http://localhost:${BackendContainerPort}/api/v1/health || exit 1'
          Essential: true

  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${AppName}-${Env}-backend'
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      EnableExecuteCommand: true
      PlatformVersion: 1.4.0
      TaskDefinition: !Ref BackendTaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref EcsServiceSecurityGroupId
          Subnets: !Split [',', !Ref PrivateSubnets]
      LoadBalancers:
        - TargetGroupArn: !Ref BackendTargetGroup
          ContainerName: backend
          ContainerPort: !Ref BackendContainerPort

  BackendScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub 'service/${EcsCluster}/${AppName}-${Env}-backend'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  BackendCpuScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${AppName}-${Env}-backend-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref BackendScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

  FrontendScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub 'service/${EcsCluster}/${AppName}-${Env}-frontend'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  FrontendCpuScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${AppName}-${Env}-frontend-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref FrontendScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: 70.0
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization

Outputs:
  AlbDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  BackendEcrRepoUri:
    Value: !GetAtt BackendEcrRepository.RepositoryUri

  FrontendEcrRepoUri:
    Value: !GetAtt FrontendEcrRepository.RepositoryUri

  ClusterName:
    Value: !Ref EcsCluster

  BackendServiceName:
    Value: !GetAtt BackendService.Name

  FrontendServiceName:
    Value: !Sub '${AppName}-${Env}-frontend'
