AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Compute Stack (ECS Fargate + ALB + WAF)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  VpcId:
    Type: String
  PublicSubnets:
    Type: String
  AppPrivateSubnets:
    Type: String
  AlbSecurityGroupId:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String
  ImageTag:
    Type: String
  DesiredCount:
    Type: Number
  BackendContainerPort:
    Type: Number
  FrontendContainerPort:
    Type: Number
  DbSecretArn:
    Type: String
  RedisEndpoint:
    Type: String
  CognitoUserPoolId:
    Type: String
  CognitoClientId:
    Type: String

Resources:
  BackendEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-backend'

  FrontendEcrRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${AppName}-${Env}-frontend'

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AppName}-${Env}-cluster'

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: RuntimePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref DbSecretArn

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}'
      RetentionInDays: 30

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AppName}-${Env}-alb'
      Scheme: internet-facing
      Type: application
      SecurityGroups: [!Ref AlbSecurityGroupId]
      Subnets: !Split [',', !Ref PublicSubnets]
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '300'

  BackendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref BackendContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /api/v1/health
      Matcher:
        HttpCode: '200-399'

  FrontendTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: !Ref FrontendContainerPort
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /healthz
      Matcher:
        HttpCode: '200-399'

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref FrontendTargetGroup

  ApiRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref HttpListener
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values: ['/api/*', '/realtime/*']
      Actions:
        - Type: forward
          TargetGroupArn: !Ref BackendTargetGroup

  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AppName}-${Env}-alb-waf'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AppName}-${Env}-alb-waf'
        SampledRequestsEnabled: true
      Rules:
        - Name: AWSManagedCommon
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: awsManagedCommon
            SampledRequestsEnabled: true

  WebAclAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !Ref ApplicationLoadBalancer
      WebACLArn: !GetAtt WebAcl.Arn

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-backend'
      RequiresCompatibilities: [FARGATE]
      Cpu: '1024'
      Memory: '2048'
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Sub '${BackendEcrRepository.RepositoryUri}:${ImageTag}'
          PortMappings:
            - ContainerPort: !Ref BackendContainerPort
          Environment:
            - Name: REDIS_ENDPOINT
              Value: !Ref RedisEndpoint
            - Name: COGNITO_USER_POOL_ID
              Value: !Ref CognitoUserPoolId
            - Name: COGNITO_CLIENT_ID
              Value: !Ref CognitoClientId
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: !Ref DbSecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: backend
        - Name: opa
          Image: public.ecr.aws/openpolicyagent/opa:latest
          Command: ['run', '--server', '/policies']
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: opa
        - Name: otel-collector
          Image: public.ecr.aws/aws-observability/aws-otel-collector:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: otel

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-worker'
      RequiresCompatibilities: [FARGATE]
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: worker
          Image: !Sub '${BackendEcrRepository.RepositoryUri}:${ImageTag}'
          Command: ['python', '-m', 'core_app.worker']
          Environment:
            - Name: REDIS_ENDPOINT
              Value: !Ref RedisEndpoint
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: !Ref DbSecretArn
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: worker

  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${AppName}-${Env}-frontend'
      RequiresCompatibilities: [FARGATE]
      Cpu: '512'
      Memory: '1024'
      NetworkMode: awsvpc
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Sub '${FrontendEcrRepository.RepositoryUri}:${ImageTag}'
          PortMappings:
            - ContainerPort: !Ref FrontendContainerPort
          Environment:
            - Name: NEXT_PUBLIC_API_BASE
              Value: ''
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: frontend

  BackendService:
    Type: AWS::ECS::Service
    DependsOn: HttpListener
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref BackendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Split [',', !Ref AppPrivateSubnets]
          SecurityGroups: [!Ref EcsServiceSecurityGroupId]
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: !Ref BackendContainerPort
          TargetGroupArn: !Ref BackendTargetGroup

  WorkerService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref WorkerTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Split [',', !Ref AppPrivateSubnets]
          SecurityGroups: [!Ref EcsServiceSecurityGroupId]

  FrontendService:
    Type: AWS::ECS::Service
    DependsOn: HttpListener
    Properties:
      Cluster: !Ref EcsCluster
      DesiredCount: 1
      LaunchType: FARGATE
      TaskDefinition: !Ref FrontendTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Split [',', !Ref AppPrivateSubnets]
          SecurityGroups: [!Ref EcsServiceSecurityGroupId]
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: !Ref FrontendContainerPort
          TargetGroupArn: !Ref FrontendTargetGroup

Outputs:
  AlbDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  BackendEcrRepoUri:
    Value: !GetAtt BackendEcrRepository.RepositoryUri
  FrontendEcrRepoUri:
    Value: !GetAtt FrontendEcrRepository.RepositoryUri
  ClusterName:
    Value: !Ref EcsCluster
