AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Enterprise Data Stack (RDS Postgres + Redis + Secrets + KMS)

Parameters:
  AppName:
    Type: String
  Env:
    Type: String
  DbInstanceClass:
    Type: String
    Default: db.t4g.large
  DbAllocatedStorage:
    Type: Number
    Default: 200
  DbMaxAllocatedStorage:
    Type: Number
    Default: 2000
  DbBackupRetentionDays:
    Type: Number
    Default: 14
  RedisNodeType:
    Type: String
    Default: cache.t4g.medium
  VpcId:
    Type: String
  PrivateSubnets:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:

# ─────────────────────────────────────────────
# KMS KEY (Shared Encryption Key)
# ─────────────────────────────────────────────

  DataKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub '${AppName}-${Env} enterprise data key'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'

  DataKmsAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AppName}-${Env}-data
      TargetKeyId: !Ref DataKmsKey

# ─────────────────────────────────────────────
# SECRETS
# ─────────────────────────────────────────────

  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/DB'
      KmsKeyId: !Ref DataKmsKey
      GenerateSecretString:
        SecretStringTemplate: '{"username":"fusion","dbname":"fusionems_quantum"}'
        GenerateStringKey: password
        PasswordLength: 40
        ExcludePunctuation: true

  RedisAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/Redis'
      KmsKeyId: !Ref DataKmsKey
      GenerateSecretString:
        PasswordLength: 40
        ExcludePunctuation: true

# ─────────────────────────────────────────────
# RDS POSTGRES
# ─────────────────────────────────────────────

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${AppName}-${Env} RDS subnet group'
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${AppName}-${Env} RDS SG'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  DbParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: postgres16
      Description: Enterprise Postgres params
      Parameters:
        log_min_duration_statement: '500'
        log_connections: '1'
        log_disconnections: '1'
        shared_preload_libraries: 'pg_stat_statements'
        rds.force_ssl: '1'

  RdsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/rds/${AppName}-${Env}'
      RetentionInDays: !If [IsProd, 90, 14]

  RdsMonitoringRole:
    Type: AWS::IAM::Role
    Condition: IsProd
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  DbInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      Engine: postgres
      EngineVersion: '16.6'
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: !Ref DbAllocatedStorage
      MaxAllocatedStorage: !Ref DbMaxAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      KmsKeyId: !Ref DataKmsKey
      AutoMinorVersionUpgrade: true
      MultiAZ: !If [IsProd, true, false]
      BackupRetentionPeriod: !Ref DbBackupRetentionDays
      PreferredBackupWindow: '04:00-05:00'
      PreferredMaintenanceWindow: 'sun:06:00-sun:07:00'
      DeletionProtection: !If [IsProd, true, false]
      CopyTagsToSnapshot: true
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
      DBParameterGroupName: !Ref DbParameterGroup
      MonitoringInterval: !If [IsProd, 60, 0]
      MonitoringRoleArn: !If [IsProd, !GetAtt RdsMonitoringRole.Arn, !Ref 'AWS::NoValue']
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: !If [IsProd, 7, 7]
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      IAMDatabaseAuthenticationEnabled: true
      MasterUsername: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:password}}'
      DBName: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:dbname}}'

# ─────────────────────────────────────────────
# REDIS ENTERPRISE HA
# ─────────────────────────────────────────────

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Redis subnet group
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  RedisParameterGroup:
    Type: AWS::ElastiCache::ParameterGroup
    Properties:
      CacheParameterGroupFamily: redis7
      Description: Enterprise Redis params
      Properties:
        notify-keyspace-events: "Ex"

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub '${AppName}-${Env}-redis'
      ReplicationGroupDescription: Enterprise Redis
      Engine: redis
      EngineVersion: '7.1'
      CacheNodeType: !Ref RedisNodeType
      NumCacheClusters: !If [IsProd, 2, 1]
      AutomaticFailoverEnabled: !If [IsProd, true, false]
      MultiAZEnabled: !If [IsProd, true, false]
      TransitEncryptionEnabled: true
      AtRestEncryptionEnabled: true
      KmsKeyId: !Ref DataKmsKey
      AuthToken: !Sub '{{resolve:secretsmanager:${RedisAuthSecret}:SecretString}}'
      SnapshotRetentionLimit: 7
      AutoMinorVersionUpgrade: true
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds:
        - !Ref RedisSecurityGroup
      CacheParameterGroupName: !Ref RedisParameterGroup
      LogDeliveryConfigurations:
        - DestinationType: cloudwatch-logs
          LogFormat: json
          LogType: engine-log

Outputs:
  DbEndpoint:
    Value: !GetAtt DbInstance.Endpoint.Address

  RedisPrimaryEndpoint:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
