AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Enterprise Data Stack (Production Safe)

Parameters:
  AppName:
    Type: String

  Env:
    Type: String

  DbInstanceClass:
    Type: String
    Default: db.t4g.large

  DbMasterUsername:
    Type: String
    Default: fusionems_admin
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]{0,15}$'
    Description: RDS master username (must not be a reserved word, start with letter, max 16 chars)

  DbName:
    Type: String
    Default: fusionems_quantum
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9_]{0,62}$'
    Description: Initial database name

  RedisNodeType:
    Type: String
    Default: cache.t4g.medium

  VpcId:
    Type: String

  PrivateSubnets:
    Type: String

  EcsServiceSecurityGroupId:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:

# ================= KMS =================

  DataKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub '${AppName}-${Env}-data-key'
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: 'kms:*'
            Resource: '*'

          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
                - secretsmanager.amazonaws.com
                - elasticache.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:DescribeKey
            Resource: '*'

  DataKmsAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AppName}-${Env}-data
      TargetKeyId: !Ref DataKmsKey

# ================= SECRETS =================

  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/DB'
      KmsKeyId: !Ref DataKmsKey
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username":"${DbMasterUsername}","dbname":"${DbName}"}'
        GenerateStringKey: password
        PasswordLength: 40
        ExcludePunctuation: true

  RedisAuthSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/Redis'
      KmsKeyId: !Ref DataKmsKey
      GenerateSecretString:
        PasswordLength: 40
        ExcludePunctuation: true

  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/AppSecrets'
      KmsKeyId: !Ref DataKmsKey
      SecretString: '{"stripe_secret_key":"REPLACE_ME","openai_api_key":"REPLACE_ME","telnyx_api_key":"REPLACE_ME","lob_api_key":"REPLACE_ME","jwt_secret_key":"REPLACE_ME"}'

# ================= RDS =================

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: RDS subnet group
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  DbInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      Engine: postgres
      EngineVersion: '16.6'
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: 200
      StorageType: gp3
      StorageEncrypted: true
      KmsKeyId: !Ref DataKmsKey
      MultiAZ: !If [IsProd, true, false]
      BackupRetentionPeriod: 14
      DeletionProtection: !If [IsProd, true, false]
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
      EnablePerformanceInsights: true
      PerformanceInsightsKMSKeyId: !Ref DataKmsKey

      MasterUsername: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:password}}'
      DBName: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:dbname}}'

# ================= REDIS =================

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Redis subnet group
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub '${AppName}-${Env}-redis'
      ReplicationGroupDescription: Enterprise Redis
      Engine: redis
      EngineVersion: '7.0'
      CacheNodeType: !Ref RedisNodeType
      NumCacheClusters: !If [IsProd, 2, 1]
      AutomaticFailoverEnabled: !If [IsProd, true, false]
      MultiAZEnabled: !If [IsProd, true, false]
      TransitEncryptionEnabled: true
      AtRestEncryptionEnabled: true
      KmsKeyId: !Ref DataKmsKey
      AuthToken: !Sub '{{resolve:secretsmanager:${RedisAuthSecret}:SecretString}}'
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds:
        - !Ref RedisSecurityGroup

Outputs:
  DbEndpoint:
    Value: !GetAtt DbInstance.Endpoint.Address

  DbSecretArn:
    Value: !Ref DbSecret

  RedisPrimaryEndpoint:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address

  RedisReplicationGroupId:
    Value: !Ref RedisReplicationGroup

  AppSecretsArn:
    Value: !Ref AppSecrets
