AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum Data Layer (RDS Postgres, Redis, Secrets)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
  AppName:
    Type: String
  DbInstanceClass:
    Type: String
  RedisNodeType:
    Type: String
  VpcId:
    Type: String
  PrivateSubnets:
    Type: CommaDelimitedList
  EcsServiceSecurityGroupId:
    Type: String

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds: !Ref PrivateSubnets

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/DB'
      GenerateSecretString:
        SecretStringTemplate: '{"username":"fusion","dbname":"fusionems_quantum"}'
        GenerateStringKey: password
        ExcludePunctuation: true

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      Engine: postgres
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: 50
      StorageEncrypted: true
      PubliclyAccessible: false
      BackupRetentionPeriod: 7
      DeletionProtection: !Equals [!Ref Env, 'prod']
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:password}}' ]]
      DBName: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:dbname}}' ]]
      VPCSecurityGroups: [!Ref DbSecurityGroup]
      DBSubnetGroupName: !Ref DbSubnetGroup

  # Redis
  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: Subnet group for Redis
      SubnetIds: !Ref PrivateSubnets

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis security group
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  RedisCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      Engine: redis
      CacheNodeType: !Ref RedisNodeType
      NumCacheNodes: 1
      VpcSecurityGroupIds: [!Ref RedisSecurityGroup]
      CacheSubnetGroupName: !Ref RedisSubnetGroup

Outputs:
  DbSecretArn:
    Value: !Ref DbSecret
  DbEndpoint:
    Value: !GetAtt DbInstance.Endpoint.Address
  DbPort:
    Value: !GetAtt DbInstance.Endpoint.Port
  RedisEndpoint:
    Value: !GetAtt RedisCluster.RedisEndpoint.Address
  RedisPort:
    Value: !GetAtt RedisCluster.RedisEndpoint.Port
