AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Data Stack (RDS + Redis + Secrets Manager)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  DbInstanceClass:
    Type: String
  RedisNodeType:
    Type: String
  VpcId:
    Type: String
  DataPrivateSubnets:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, prod]

Resources:
  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${AppName}-${Env} RDS subnet group'
      SubnetIds: !Split [',', !Ref DataPrivateSubnets]

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Postgres access from ECS only
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis access from ECS only
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/db'
      GenerateSecretString:
        SecretStringTemplate: '{"username":"fusion","dbname":"fusionems_quantum"}'
        GenerateStringKey: password
        ExcludePunctuation: true

  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${AppName}-${Env}-postgres'
      Engine: postgres
      EngineVersion: '16.3'
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: 100
      StorageType: gp3
      StorageEncrypted: true
      PubliclyAccessible: false
      MultiAZ: !If [IsProd, true, false]
      BackupRetentionPeriod: !If [IsProd, 14, 3]
      DeletionProtection: !If [IsProd, true, false]
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups: [!Ref DbSecurityGroup]
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:password}}' ]]
      DBName: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:dbname}}' ]]

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub '${AppName}-${Env} redis subnet group'
      SubnetIds: !Split [',', !Ref DataPrivateSubnets]

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub '${AppName}-${Env}-redis'
      ReplicationGroupDescription: !Sub '${AppName}-${Env} redis replication group'
      Engine: redis
      CacheNodeType: !Ref RedisNodeType
      NumCacheClusters: 2
      AutomaticFailoverEnabled: true
      MultiAZEnabled: true
      TransitEncryptionEnabled: true
      AtRestEncryptionEnabled: true
      SnapshotRetentionLimit: !If [IsProd, 7, 1]
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds: [!Ref RedisSecurityGroup]

Outputs:
  DbSecretArn:
    Value: !Ref DbSecret
  RedisEndpoint:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
