AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Data Stack (RDS Postgres + Redis + Secrets Manager)

Parameters:
  AppName:
    Type: String
  Env:
    Type: String
  DbInstanceClass:
    Type: String
    Default: db.t4g.medium
  DbAllocatedStorage:
    Type: Number
    Default: 100
  DbMaxAllocatedStorage:
    Type: Number
    Default: 1000
  DbBackupRetentionDays:
    Type: Number
    Default: 7
  DbEnablePerformanceInsights:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'true'
  DbMultiAZ:
    Type: String
    AllowedValues: ['true', 'false']
    Default: 'false'
  RedisNodeType:
    Type: String
    Default: cache.t4g.small
  RedisNumNodes:
    Type: Number
    Default: 1
  VpcId:
    Type: String
  PrivateSubnets:
    Type: String
  EcsServiceSecurityGroupId:
    Type: String

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']
  EnablePI: !Equals [!Ref DbEnablePerformanceInsights, 'true']
  EnableMultiAZ: !Or [!Equals [!Ref DbMultiAZ, 'true'], !Equals [!Ref Env, prod]]

Resources:

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${AppName}-${Env} RDS subnet group'
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${AppName}-${Env} RDS SG'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${AppName}-${Env} Redis SG'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0

  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/DB'
      Description: !Sub '${AppName} ${Env} database credentials'
      GenerateSecretString:
        SecretStringTemplate: '{"username":"fusion","dbname":"fusionems_quantum"}'
        GenerateStringKey: password
        ExcludePunctuation: true

  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/App'
      Description: !Sub '${AppName} ${Env} application secrets (Stripe, Telnyx, LOB, SES, OpenAI, OfficeAlly)'
      SecretString: !Sub |
        {
          "stripe_secret_key": "REPLACE_WITH_STRIPE_SECRET_KEY",
          "stripe_webhook_secret": "REPLACE_WITH_STRIPE_WEBHOOK_SECRET",
          "stripe_publishable_key": "REPLACE_WITH_STRIPE_PUBLISHABLE_KEY",
          "telnyx_api_key": "REPLACE_WITH_TELNYX_API_KEY",
          "telnyx_webhook_public_key": "REPLACE_WITH_TELNYX_WEBHOOK_PUBLIC_KEY",
          "telnyx_from_number": "REPLACE_WITH_TELNYX_FROM_NUMBER",
          "telnyx_messaging_profile_id": "REPLACE_WITH_TELNYX_MESSAGING_PROFILE_ID",
          "lob_api_key": "REPLACE_WITH_LOB_API_KEY",
          "lob_webhook_secret": "REPLACE_WITH_LOB_WEBHOOK_SECRET",
          "openai_api_key": "REPLACE_WITH_OPENAI_API_KEY",
          "officeally_sftp_host": "REPLACE_WITH_OFFICEALLY_SFTP_HOST",
          "officeally_sftp_username": "REPLACE_WITH_OFFICEALLY_SFTP_USERNAME",
          "officeally_sftp_password": "REPLACE_WITH_OFFICEALLY_SFTP_PASSWORD",
          "jwt_secret_key": "REPLACE_WITH_STRONG_RANDOM_SECRET_64CHARS",
          "ses_from_email": "noreply@fusionemsquantum.com"
        }

  RdsMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AppName}-${Env}-rds-monitoring'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

  DbParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Sub '${AppName}-${Env} postgres params'
      Family: postgres16
      Parameters:
        log_min_duration_statement: '500'
        log_statement: 'none'
        log_connections: '1'
        log_disconnections: '1'

  DbInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      Engine: postgres
      EngineVersion: '16.3'
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: !Ref DbAllocatedStorage
      MaxAllocatedStorage: !Ref DbMaxAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      PubliclyAccessible: false
      MultiAZ: !If [EnableMultiAZ, true, false]
      BackupRetentionPeriod: !If [IsProd, !Ref DbBackupRetentionDays, 1]
      DeletionProtection: !If [IsProd, true, false]
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups:
        - !Ref DbSecurityGroup
      DBParameterGroupName: !Ref DbParameterGroup
      MonitoringInterval: !If [IsProd, 60, 0]
      MonitoringRoleArn: !If [IsProd, !GetAtt RdsMonitoringRole.Arn, !Ref 'AWS::NoValue']
      EnablePerformanceInsights: !If [EnablePI, true, false]
      EnableCloudwatchLogsExports:
        - postgresql
        - upgrade
      MasterUsername: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:password}}'
      DBName: !Sub '{{resolve:secretsmanager:${DbSecret}:SecretString:dbname}}'

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub '${AppName}-${Env} Redis subnet group'
      SubnetIds: !Split [',', !Ref PrivateSubnets]

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub '${AppName}-${Env}-redis'
      ReplicationGroupDescription: !Sub '${AppName}-${Env} Redis replication group'
      Engine: redis
      CacheNodeType: !Ref RedisNodeType
      NumCacheClusters: !Ref RedisNumNodes
      AutomaticFailoverEnabled: false
      MultiAZEnabled: false
      TransitEncryptionEnabled: true
      AtRestEncryptionEnabled: true
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds:
        - !Ref RedisSecurityGroup

Outputs:
  DbSecretArn:
    Value: !Ref DbSecret
    Export:
      Name: !Sub '${AppName}-${Env}-DbSecretArn'

  AppSecretsArn:
    Value: !Ref AppSecrets
    Export:
      Name: !Sub '${AppName}-${Env}-AppSecretsArn'

  DbInstanceId:
    Value: !Ref DbInstance
    Export:
      Name: !Sub '${AppName}-${Env}-DbInstanceId'

  DbEndpoint:
    Value: !GetAtt DbInstance.Endpoint.Address

  DbPort:
    Value: !GetAtt DbInstance.Endpoint.Port

  RedisReplicationGroupId:
    Value: !Ref RedisReplicationGroup
    Export:
      Name: !Sub '${AppName}-${Env}-RedisClusterId'

  RedisPrimaryEndpoint:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
    Export:
      Name: !Sub '${AppName}-${Env}-RedisPrimaryEndpoint'

  RedisPort:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Port
