AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Data (RDS, Redis, S3, Secrets)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  VpcId:
    Type: String
  PrivateSubnets:
    Type: CommaDelimitedList
  EcsServiceSecurityGroupId:
    Type: String
  DbInstanceClass:
    Type: String
    Default: db.t4g.medium
  RedisNodeType:
    Type: String
    Default: cache.t4g.small

Conditions:
  IsProd: !Equals [!Ref Env, prod]

Resources:
  DbSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/db'
      GenerateSecretString:
        SecretStringTemplate: '{"username":"fusionems","dbname":"fusionems"}'
        GenerateStringKey: password
        ExcludePunctuation: true

  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/app-secrets'
      SecretString: '{}'

  DbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${AppName}-${Env}-db-subnets'
      SubnetIds: !Ref PrivateSubnets

  DbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS ingress only from ECS services
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  DbInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      Engine: postgres
      DBInstanceClass: !Ref DbInstanceClass
      AllocatedStorage: '100'
      StorageType: gp3
      StorageEncrypted: true
      PubliclyAccessible: false
      BackupRetentionPeriod: !If [IsProd, 14, 7]
      DeletionProtection: !If [IsProd, true, false]
      MultiAZ: !If [IsProd, true, false]
      DBSubnetGroupName: !Ref DbSubnetGroup
      VPCSecurityGroups: [!Ref DbSecurityGroup]
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:username}}']]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:password}}']]
      DBName: !Join ['', ['{{resolve:secretsmanager:', !Ref DbSecret, ':SecretString:dbname}}']]

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Sub '${AppName}-${Env}-redis-subnets'
      SubnetIds: !Ref PrivateSubnets

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Redis ingress only from ECS services
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref EcsServiceSecurityGroupId

  RedisReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: !Sub '${AppName}-${Env}-redis'
      ReplicationGroupDescription: !Sub '${AppName}-${Env}-redis'
      Engine: redis
      CacheNodeType: !Ref RedisNodeType
      NumCacheClusters: !If [IsProd, 2, 1]
      MultiAZEnabled: !If [IsProd, true, false]
      AutomaticFailoverEnabled: !If [IsProd, true, false]
      TransitEncryptionEnabled: true
      AtRestEncryptionEnabled: true
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds: [!Ref RedisSecurityGroup]

  DocsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${Env}-docs-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  ExportsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${Env}-exports-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: retention
            Status: Enabled
            ExpirationInDays: 2555

Outputs:
  DbSecretArn:
    Value: !Ref DbSecret
  AppSecretsArn:
    Value: !Ref AppSecrets
  DbInstanceId:
    Value: !Ref DbInstance
  RedisEndpoint:
    Value: !GetAtt RedisReplicationGroup.PrimaryEndPoint.Address
  RedisReplicationGroupId:
    Value: !Ref RedisReplicationGroup
  DocsBucketName:
    Value: !Ref DocsBucket
  ExportsBucketName:
    Value: !Ref ExportsBucket
