AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Enterprise Edge Stack (CloudFront + Route53 + WAF)

Parameters:
  Env:
    Type: String

  AppName:
    Type: String

  RootDomainName:
    Type: String

  ApiDomainName:
    Type: String

  HostedZoneId:
    Type: String

  AcmCertificateArnUsEast1:
    Type: String

  AlbDnsName:
    Type: String

Resources:

# ================= LOG BUCKET =================

  CloudFrontLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppName}-${Env}-${AWS::AccountId}-cf-logs'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

# ================= WAF =================

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AppName}-${Env}-edge-waf'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AppName}-${Env}-waf'
        SampledRequestsEnabled: true
      Rules:
        - Name: AWSManagedCommon
          Priority: 1
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: common
            SampledRequestsEnabled: true

# ================= SECURITY HEADERS =================

  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${AppName}-${Env}-security-headers'
        SecurityHeadersConfig:
          StrictTransportSecurity:
            Override: true
            IncludeSubdomains: true
            Preload: true
            AccessControlMaxAgeSec: 63072000
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true

# ================= CACHE POLICIES =================

  NoCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${AppName}-${Env}-no-cache'
        DefaultTTL: 0
        MinTTL: 0
        MaxTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          HeadersConfig:
            HeaderBehavior: allViewer
          QueryStringsConfig:
            QueryStringBehavior: all
          CookiesConfig:
            CookieBehavior: all

  StaticCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${AppName}-${Env}-static'
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: none
          CookiesConfig:
            CookieBehavior: none

# ================= DISTRIBUTION =================

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        WebACLId: !GetAtt WebACL.Arn
        Aliases:
          - !Ref RootDomainName
          - !Ref ApiDomainName
        DefaultRootObject: index.html

        Logging:
          Bucket: !Sub '${CloudFrontLogsBucket}.s3.amazonaws.com'
          IncludeCookies: false

        Origins:
          - Id: AlbOrigin
            DomainName: !Ref AlbDnsName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
              OriginSSLProtocols:
                - TLSv1.2

        DefaultCacheBehavior:
          TargetOriginId: AlbOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD]
          Compress: true
          CachePolicyId: !Ref StaticCachePolicy
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy

        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: AlbOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachePolicyId: !Ref NoCachePolicy

        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArnUsEast1
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

# ================= ROUTE53 =================

  RootDomainRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RootDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ApiDomainRecordA:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApiDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontDistributionId:
    Value: !Ref CloudFrontDistribution
