AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum Edge (CloudFront + WAF + Route53)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
  AppName:
    Type: String

  RootDomainName:
    Type: String
    Description: Apex domain for landing/UI (e.g., fusionemsquantum.com)

  ApiDomainName:
    Type: String
    Description: API domain (e.g., api.fusionemsquantum.com)

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for the domain

  AlbDnsName:
    Type: String
    Description: Public DNS name of the ALB (no https://)

  AcmCertificateArnUsEast1:
    Type: String
    Description: ACM certificate ARN in us-east-1 covering RootDomainName and ApiDomainName

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:
  # ----------------------------
  # WAF (CloudFront scope)
  # ----------------------------
  WebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AppName}-${Env}-waf'
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AppName}-${Env}-waf'
        SampledRequestsEnabled: true
      Rules:
        - Name: AWSManagedCommonRuleSet
          Priority: 10
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AppName}-${Env}-waf-common'
            SampledRequestsEnabled: true
        - Name: AWSManagedKnownBadInputs
          Priority: 20
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AppName}-${Env}-waf-badinputs'
            SampledRequestsEnabled: true
        - Name: RateLimit
          Priority: 30
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          VisibilityConfig:
            CloudWatchMetricsEnabled: true
            MetricName: !Sub '${AppName}-${Env}-waf-ratelimit'
            SampledRequestsEnabled: true

  # ----------------------------
  # Cache + Origin Request Policies
  # ----------------------------
  ApiNoCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${AppName}-${Env}-api-nocache'
        DefaultTTL: 0
        MaxTTL: 0
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: all
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Authorization
              - Content-Type
              - Origin
              - Referer
              - User-Agent
              - X-Requested-With
          QueryStringsConfig:
            QueryStringBehavior: all

  UiCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub '${AppName}-${Env}-ui-cache'
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 0
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true
          CookiesConfig:
            CookieBehavior: all
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: all

  UiOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${AppName}-${Env}-ui-originreq'
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: whitelist
          Headers:
            - Host
            - CloudFront-Viewer-Country
            - CloudFront-Forwarded-Proto
            - User-Agent
        QueryStringsConfig:
          QueryStringBehavior: all

  ApiOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${AppName}-${Env}-api-originreq'
        CookiesConfig:
          CookieBehavior: all
        HeadersConfig:
          HeaderBehavior: allViewer
        QueryStringsConfig:
          QueryStringBehavior: all

  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub '${AppName}-${Env}-security-headers'
        SecurityHeadersConfig:
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: same-origin
            Override: true
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 31536000
            IncludeSubdomains: true
            Preload: true
            Override: true
          XSSProtection:
            Protection: true
            ModeBlock: true
            Override: true

  # ----------------------------
  # CloudFront Distribution (single distribution handles both domains)
  # Origins: same ALB, different behaviors.
  # ----------------------------
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        Aliases:
          - !Ref RootDomainName
          - !Ref ApiDomainName

        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArnUsEast1
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        DefaultRootObject: ''

        Origins:
          - Id: alb-origin
            DomainName: !Ref AlbDnsName
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
              HTTPPort: 80
              HTTPSPort: 443
              OriginSSLProtocols: [TLSv1.2]

        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD, OPTIONS]
          Compress: true
          CachePolicyId: !Ref UiCachePolicy
          OriginRequestPolicyId: !Ref UiOriginRequestPolicy
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy

        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: alb-origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
            CachedMethods: [GET, HEAD, OPTIONS]
            Compress: true
            CachePolicyId: !Ref ApiNoCachePolicy
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy
            ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy

        WebACLId: !GetAtt WebAcl.Arn

  # ----------------------------
  # Route53 Records
  # ----------------------------
  RootARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RootDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront HostedZoneId (global)

  RootAAAARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RootDomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ApiARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApiDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ApiAAAARecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApiDomainName
      Type: AAAA
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  DistributionId:
    Value: !Ref Distribution
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName
  WebAclArn:
    Value: !GetAtt WebAcl.Arn
