AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Edge (CloudFront, WAF, Route53)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  RootDomainName:
    Type: String
  ApiDomainName:
    Type: String
  HostedZoneId:
    Type: String
  AcmCertificateArnUsEast1:
    Type: String
  AlbDnsName:
    Type: String

Resources:
  EdgeWebAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AppName}-${Env}-edge-webacl'
      Scope: CLOUDFRONT
      DefaultAction: { Allow: {} }
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: !Sub '${AppName}-${Env}-edge-webacl'
      Rules:
        - Name: managed-common
          Priority: 1
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig: { CloudWatchMetricsEnabled: true, SampledRequestsEnabled: true, MetricName: managed-common }
        - Name: managed-known-bad-inputs
          Priority: 2
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig: { CloudWatchMetricsEnabled: true, SampledRequestsEnabled: true, MetricName: managed-known-bad-inputs }
        - Name: managed-sqli
          Priority: 3
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig: { CloudWatchMetricsEnabled: true, SampledRequestsEnabled: true, MetricName: managed-sqli }
        - Name: rate-all
          Priority: 10
          Action: { Block: {} }
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          VisibilityConfig: { CloudWatchMetricsEnabled: true, SampledRequestsEnabled: true, MetricName: rate-all }
        - Name: rate-public-path
          Priority: 11
          Action: { Block: {} }
          Statement:
            RateBasedStatement:
              Limit: 300
              AggregateKeyType: IP
              ScopeDownStatement:
                ByteMatchStatement:
                  SearchString: '/public/'
                  FieldToMatch: { UriPath: {} }
                  TextTransformations: [{ Type: NONE, Priority: 0 }]
                  PositionalConstraint: STARTS_WITH
          VisibilityConfig: { CloudWatchMetricsEnabled: true, SampledRequestsEnabled: true, MetricName: rate-public }
        - Name: rate-webhook-path
          Priority: 12
          Action: { Block: {} }
          Statement:
            RateBasedStatement:
              Limit: 120
              AggregateKeyType: IP
              ScopeDownStatement:
                ByteMatchStatement:
                  SearchString: '/webhooks/'
                  FieldToMatch: { UriPath: {} }
                  TextTransformations: [{ Type: NONE, Priority: 0 }]
                  PositionalConstraint: STARTS_WITH
          VisibilityConfig: { CloudWatchMetricsEnabled: true, SampledRequestsEnabled: true, MetricName: rate-webhooks }

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: [!Ref RootDomainName, !Ref ApiDomainName]
        WebACLId: !GetAtt EdgeWebAcl.Arn
        Origins:
          - Id: alb-origin
            DomainName: !Ref AlbDnsName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS, PUT, POST, PATCH, DELETE]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: true
            Cookies: { Forward: all }
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArnUsEast1
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  RootDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RootDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ApiDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApiDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
  WebAclArn:
    Value: !GetAtt EdgeWebAcl.Arn
