AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Edge Stack (CloudFront + Route53 + ALB HTTPS)

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  RootDomainName:
    Type: String
  ApiDomainName:
    Type: String
  HostedZoneId:
    Type: String
  AcmCertificateArnUsEast1:
    Type: String
  AlbDnsName:
    Type: String

Resources:

  ########################################
  # CLOUDFRONT DISTRIBUTION
  ########################################

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref RootDomainName
          - !Ref ApiDomainName
        DefaultRootObject: index.html
        Origins:
          - Id: AlbOrigin
            DomainName: !Ref AlbDnsName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: AlbOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: all
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArnUsEast1
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  ########################################
  # ROUTE53 RECORDS
  ########################################

  RootDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RootDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  ApiDomainRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref ApiDomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:

  CloudFrontDomain:
    Value: !GetAtt CloudFrontDistribution.DomainName
