AWSTemplateFormatVersion: "2010-09-09"
Description: FusionEMS KitLink AR — Enterprise Production Hardened Stack

Parameters:
  AppName:
    Type: String
    Default: fusionems

  Stage:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]

  DatabaseUrl:
    Type: String
    NoEcho: true

  OpenAiApiKey:
    Type: String
    NoEcho: true

  LambdaCodeBucket:
    Type: String

  LambdaCodeKey:
    Type: String
    Default: kitlink/lambda/kitlink_worker.zip

  AlarmEmail:
    Type: String
    Default: ""

Conditions:
  HasAlarmEmail: !Not [!Equals [!Ref AlarmEmail, ""]]

Resources:

# ================= KMS =================

  KitLinkKmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub "${AppName}-${Stage} KitLink encryption key"
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"

  KitLinkKmsAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AppName}-${Stage}-kitlink"
      TargetKeyId: !Ref KitLinkKmsKey

# ================= S3 =================

  KitLinkArtifactsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${AppName}-${Stage}-${AWS::AccountId}-kitlink-artifacts"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KitLinkKmsKey

# ================= SQS =================

  KitLinkOcrDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AppName}-${Stage}-kitlink-ocr-dlq.fifo"
      FifoQueue: true
      KmsMasterKeyId: !Ref KitLinkKmsKey

  KitLinkOcrQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AppName}-${Stage}-kitlink-ocr.fifo"
      FifoQueue: true
      VisibilityTimeout: 300
      KmsMasterKeyId: !Ref KitLinkKmsKey
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt KitLinkOcrDLQ.Arn
        maxReceiveCount: 3

# ================= IAM =================

  KitLinkLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: KitLinkLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${KitLinkArtifactsBucket}/*"
              - Effect: Allow
                Action:
                  - sqs:*
                Resource:
                  - !GetAtt KitLinkOcrQueue.Arn
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt KitLinkKmsKey.Arn

# ================= LAMBDA =================

  KitLinkOcrLambda:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.12
      Handler: core_app.workers.kitlink_worker.lambda_handler
      Role: !GetAtt KitLinkLambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          OPENAI_API_KEY: !Ref OpenAiApiKey
          KITLINK_OCR_QUEUE_URL: !Ref KitLinkOcrQueue

  KitLinkOcrEventSourceMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt KitLinkOcrQueue.Arn
      FunctionName: !GetAtt KitLinkOcrLambda.Arn
      BatchSize: 1

# ================= ALARMS =================

  KitLinkAlarmTopic:
    Type: AWS::SNS::Topic
    Condition: HasAlarmEmail
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlarmEmail

  KitLinkOcrDLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: HasAlarmEmail
    Properties:
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt KitLinkOcrDLQ.QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref KitLinkAlarmTopic

Outputs:
  KitLinkArtifactsBucketName:
    Value: !Ref KitLinkArtifactsBucket

  KitLinkOcrQueueUrl:
    Value: !Ref KitLinkOcrQueue

  KitLinkLambdaExecutionRoleArn:
    Value: !GetAtt KitLinkLambdaExecutionRole.Arn
