AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Observability Stack (CloudWatch + SNS + Dashboard)

Parameters:
  AppName:
    Type: String

  Env:
    Type: String

  AlertEmail:
    Type: String
    Default: joshua.j.wendorf@fusionemsquantum.com

  EcsClusterName:
    Type: String

  BackendServiceName:
    Type: String

  AlbFullName:
    Type: String

  BackendTargetGroupFullName:
    Type: String

  DbInstanceId:
    Type: String

  RedisClusterId:
    Type: String

  RootDomainName:
    Type: String

  ApiDomainName:
    Type: String

  LogRetentionDays:
    Type: Number
    Default: 30

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:

  # ================= SNS =================

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AppName}-${Env}-alerts'

  AlertSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertTopic
      Protocol: email
      Endpoint: !Ref AlertEmail

  # ================= Logs =================

  AuditLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}/audit'
      RetentionInDays: !Ref LogRetentionDays

  # ================= ALB Alarms =================

  Alb5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-ALB-5XX'
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref AlbFullName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  BackendTarget5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-Target-5XX'
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_Target_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref AlbFullName
        - Name: TargetGroup
          Value: !Ref BackendTargetGroupFullName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # ================= ECS =================

  BackendCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-Backend-CPU'
      Namespace: AWS/ECS
      MetricName: CPUUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref EcsClusterName
        - Name: ServiceName
          Value: !Ref BackendServiceName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: !If [IsProd, 80, 90]
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  BackendMemAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-Backend-MEM'
      Namespace: AWS/ECS
      MetricName: MemoryUtilization
      Dimensions:
        - Name: ClusterName
          Value: !Ref EcsClusterName
        - Name: ServiceName
          Value: !Ref BackendServiceName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: !If [IsProd, 80, 90]
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # ================= RDS =================

  RdsCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-RDS-CPU'
      Namespace: AWS/RDS
      MetricName: CPUUtilization
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DbInstanceId
      Statistic: Average
      Period: 60
      EvaluationPeriods: 10
      Threshold: !If [IsProd, 75, 90]
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # ================= Redis =================

  RedisCpuAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-Redis-CPU'
      Namespace: AWS/ElastiCache
      MetricName: EngineCPUUtilization
      Dimensions:
        - Name: ReplicationGroupId
          Value: !Ref RedisClusterId
      Statistic: Average
      Period: 60
      EvaluationPeriods: 10
      Threshold: !If [IsProd, 75, 90]
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

  # ================= Dashboard =================

  OpsDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${AppName}-${Env}-ops'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "text",
              "x": 0,
              "y": 0,
              "width": 24,
              "height": 2,
              "properties": {
                "markdown": "# ${AppName} (${Env})\\nFrontend: https://${RootDomainName}\\nAPI: https://${ApiDomainName}"
              }
            }
          ]
        }

Outputs:
  AlertTopicArn:
    Value: !Ref AlertTopic

  DashboardName:
    Value: !Ref OpsDashboard
