AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Observability alarms and log groups

Parameters:
  Env:
    Type: String
  AppName:
    Type: String
  ClusterName:
    Type: String
  BackendServiceName:
    Type: String
  FrontendServiceName:
    Type: String
  DbInstanceId:
    Type: String
  RedisReplicationGroupId:
    Type: String
  AlbFullName:
    Type: String
  BackendTargetGroupFullName:
    Type: String

Resources:
  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}/backend'
      RetentionInDays: 30

  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/${AppName}/${Env}/frontend'
      RetentionInDays: 30

  Alb5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-alb-5xx'
      Namespace: AWS/ApplicationELB
      MetricName: HTTPCode_ELB_5XX_Count
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref AlbFullName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  BackendLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-backend-latency'
      Namespace: AWS/ApplicationELB
      MetricName: TargetResponseTime
      Dimensions:
        - Name: LoadBalancer
          Value: !Ref AlbFullName
        - Name: TargetGroup
          Value: !Ref BackendTargetGroupFullName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 1.5
      ComparisonOperator: GreaterThanThreshold

  RdsConnectionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-rds-connections'
      Namespace: AWS/RDS
      MetricName: DatabaseConnections
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DbInstanceId
      Statistic: Average
      Period: 60
      EvaluationPeriods: 5
      Threshold: 120
      ComparisonOperator: GreaterThanThreshold

  RedisEvictionsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-redis-evictions'
      Namespace: AWS/ElastiCache
      MetricName: Evictions
      Dimensions:
        - Name: ReplicationGroupId
          Value: !Ref RedisReplicationGroupId
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 3
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold

  QueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AppName}-${Env}-queue-depth'
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !Sub '${AppName}-${Env}-jobs'
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold

Outputs:
  BackendLogGroupName:
    Value: !Ref BackendLogGroup
  FrontendLogGroupName:
    Value: !Ref FrontendLogGroup
