AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Root Stack

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: prod

  AppName:
    Type: String
    Default: fusionems

  RootDomainName:
    Type: String
    Default: app.fusionemsquantum.com

  ApiDomainName:
    Type: String
    Default: api.fusionemsquantum.com

  HostedZoneId:
    Type: String

  ImageTagFrontend:
    Type: String
    Default: latest

  ImageTagBackend:
    Type: String
    Default: latest

  NestedTemplatesBucket:
    Type: String

Resources:

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env

  DataStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: data.yml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: cognito.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataStack
      - CognitoStack
    Properties:
      TemplateURL: compute.yml
      Parameters:
        AppName: !Ref AppName
        Env: !Ref Env
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnets: !GetAtt NetworkStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        ImageTagFrontend: !Ref ImageTagFrontend
        ImageTagBackend: !Ref ImageTagBackend
        DbSecretArn: !GetAtt DataStack.Outputs.DbSecretArn
        AppSecretsArn: !GetAtt DataStack.Outputs.AppSecretsArn
        RedisPrimaryEndpoint: !GetAtt DataStack.Outputs.RedisPrimaryEndpoint
        CognitoUserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        CognitoClientId: !GetAtt CognitoStack.Outputs.UserPoolClientId

  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: edge.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
        HostedZoneId: !Ref HostedZoneId
        AlbDnsName: !GetAtt ComputeStack.Outputs.AlbDnsName

Outputs:
  CloudFrontDomain:
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDomain
