AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Root stack

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev
  AppName:
    Type: String
    Default: fusionems-quantum
  RootDomainName:
    Type: String
    Default: fusionemsquantum.com
  ApiDomainName:
    Type: String
    Default: api.fusionemsquantum.com
  HostedZoneId:
    Type: String
  AcmCertificateArnUsEast1:
    Type: String
  ImageTag:
    Type: String
    Default: latest
  DesiredCount:
    Type: Number
    Default: 2
  DbInstanceClass:
    Type: String
    Default: db.t4g.medium
  RedisNodeType:
    Type: String
    Default: cache.t4g.small

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName

  DataStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: data.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        DbInstanceClass: !Ref DbInstanceClass
        RedisNodeType: !Ref RedisNodeType
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateDataSubnets
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: cognito.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName

  SesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: ses.yml
      Parameters:
        RootDomainName: !Ref RootDomainName

  BootstrapStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataStack
    Properties:
      TemplateURL: bootstrap.yml
      Parameters:
        AppSecretsArn: !GetAtt DataStack.Outputs.AppSecretsArn

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [DataStack, CognitoStack]
    Properties:
      TemplateURL: compute.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnets: !GetAtt NetworkStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        ImageTag: !Ref ImageTag
        DesiredCount: !Ref DesiredCount
        DbSecretArn: !GetAtt DataStack.Outputs.DbSecretArn
        AppSecretsArn: !GetAtt DataStack.Outputs.AppSecretsArn
        RedisEndpoint: !GetAtt DataStack.Outputs.RedisEndpoint
        CognitoUserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        CognitoClientId: !GetAtt CognitoStack.Outputs.UserPoolClientId

  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: edge.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
        HostedZoneId: !Ref HostedZoneId
        AcmCertificateArnUsEast1: !Ref AcmCertificateArnUsEast1
        AlbDnsName: !GetAtt ComputeStack.Outputs.AlbDnsName

  ObservabilityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: observability.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        ClusterName: !GetAtt ComputeStack.Outputs.ClusterName
        BackendServiceName: !GetAtt ComputeStack.Outputs.BackendServiceName
        FrontendServiceName: !GetAtt ComputeStack.Outputs.FrontendServiceName
        DbInstanceId: !GetAtt DataStack.Outputs.DbInstanceId
        RedisReplicationGroupId: !GetAtt DataStack.Outputs.RedisReplicationGroupId
        AlbFullName: !GetAtt ComputeStack.Outputs.AlbFullName
        BackendTargetGroupFullName: !GetAtt ComputeStack.Outputs.BackendTargetGroupFullName

Outputs:
  ClusterName:
    Value: !GetAtt ComputeStack.Outputs.ClusterName
  BackendServiceName:
    Value: !GetAtt ComputeStack.Outputs.BackendServiceName
  FrontendServiceName:
    Value: !GetAtt ComputeStack.Outputs.FrontendServiceName
  WorkerServiceName:
    Value: !GetAtt ComputeStack.Outputs.WorkerServiceName
  PrivateSubnets:
    Value: !GetAtt NetworkStack.Outputs.PrivateSubnets
  EcsServiceSecurityGroupId:
    Value: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
  AlbDnsName:
    Value: !GetAtt ComputeStack.Outputs.AlbDnsName
  CloudFrontDomain:
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDomain
  DbSecretArn:
    Value: !GetAtt DataStack.Outputs.DbSecretArn
  AppSecretsArn:
    Value: !GetAtt DataStack.Outputs.AppSecretsArn
  RedisEndpoint:
    Value: !GetAtt DataStack.Outputs.RedisEndpoint
  BackendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.BackendEcrRepoUri
  FrontendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.FrontendEcrRepoUri
  SesIdentityArn:
    Value: !GetAtt SesStack.Outputs.SesIdentityArn
