AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Founder Command Platform (Root Nested Stack - Hardened Phase 1)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev

  AppName:
    Type: String
    Default: fusionems-quantum

  RootDomainName:
    Type: String
    Default: fusionemsquantum.com

  ApiDomainName:
    Type: String
    Default: api.fusionemsquantum.com

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for fusionemsquantum.com

  AcmCertificateArnUsEast1:
    Type: String
    Description: ACM certificate ARN in us-east-1 covering RootDomainName and ApiDomainName

  ImageTag:
    Type: String
    Default: latest

  DesiredCount:
    Type: Number
    Default: 2

  BackendContainerPort:
    Type: Number
    Default: 8000

  FrontendContainerPort:
    Type: Number
    Default: 3000

  DbInstanceClass:
    Type: String
    Default: db.t4g.medium

  RedisNodeType:
    Type: String
    Default: cache.t4g.small

Resources:

  ########################################
  # NETWORK
  ########################################

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  ########################################
  # DATA LAYER (RDS + REDIS + SECRETS)
  ########################################

  DataStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: data.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        DbInstanceClass: !Ref DbInstanceClass
        RedisNodeType: !Ref RedisNodeType
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        DataPrivateSubnets: !GetAtt NetworkStack.Outputs.DataPrivateSubnets
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  ########################################
  # AUTH (COGNITO)
  ########################################

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: cognito.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  ########################################
  # COMPUTE (ECS + ALB + ECR)
  ########################################

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataStack
      - CognitoStack
    Properties:
      TemplateURL: compute.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnets: !GetAtt NetworkStack.Outputs.PublicSubnets
        AppPrivateSubnets: !GetAtt NetworkStack.Outputs.AppPrivateSubnets
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        ImageTag: !Ref ImageTag
        DesiredCount: !Ref DesiredCount
        BackendContainerPort: !Ref BackendContainerPort
        FrontendContainerPort: !Ref FrontendContainerPort
        DbSecretArn: !GetAtt DataStack.Outputs.DbSecretArn
        RedisEndpoint: !GetAtt DataStack.Outputs.RedisEndpoint
        CognitoUserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        CognitoClientId: !GetAtt CognitoStack.Outputs.UserPoolClientId
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  ########################################
  # EDGE (CLOUDFRONT + ROUTE53)
  ########################################

  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: edge.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
        HostedZoneId: !Ref HostedZoneId
        AcmCertificateArnUsEast1: !Ref AcmCertificateArnUsEast1
        AlbDnsName: !GetAtt ComputeStack.Outputs.AlbDnsName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  ########################################
  # OBSERVABILITY (PROMETHEUS / GRAFANA / CW ALARMS)
  ########################################

  ObservabilityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: observability.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        ClusterName: !GetAtt ComputeStack.Outputs.ClusterName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

Outputs:

  RootDomainName:
    Value: !Ref RootDomainName

  ApiDomainName:
    Value: !Ref ApiDomainName

  CloudFrontDomain:
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDomain

  BackendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.BackendEcrRepoUri

  FrontendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.FrontendEcrRepoUri

  CognitoUserPoolId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolId

  CognitoUserPoolClientId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId
