AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Founder Command Platform (Root Nested Stack)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev
  AppName:
    Type: String
    Default: fusionems-quantum
  RootDomainName:
    Type: String
    Default: fusionemsquantum.com
  ApiDomainName:
    Type: String
    Default: api.fusionemsquantum.com
  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID for fusionemsquantum.com
  AcmCertificateArnUsEast1:
    Type: String
    Description: ACM certificate ARN in us-east-1 covering RootDomainName and ApiDomainName (required for CloudFront)
  ImageTag:
    Type: String
    Default: latest
  DesiredCount:
    Type: Number
    Default: 2
  BackendContainerPort:
    Type: Number
    Default: 8000
  FrontendContainerPort:
    Type: Number
    Default: 3000
  DbInstanceClass:
    Type: String
    Default: db.t4g.medium
  RedisNodeType:
    Type: String
    Default: cache.t4g.small

Resources:
  # NOTE: GitHub Actions must run 'aws cloudformation package' so local nested templates become S3 TemplateURL links.
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: network.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName

  DataStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: data.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        DbInstanceClass: !Ref DbInstanceClass
        RedisNodeType: !Ref RedisNodeType
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: compute.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnets: !GetAtt NetworkStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        ImageTag: !Ref ImageTag
        DesiredCount: !Ref DesiredCount
        BackendContainerPort: !Ref BackendContainerPort
        FrontendContainerPort: !Ref FrontendContainerPort
        DbSecretArn: !GetAtt DataStack.Outputs.DbSecretArn
        RedisEndpoint: !GetAtt DataStack.Outputs.RedisEndpoint

  EdgeStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: edge.yml
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
        HostedZoneId: !Ref HostedZoneId
        AcmCertificateArnUsEast1: !Ref AcmCertificateArnUsEast1
        AlbDnsName: !GetAtt ComputeStack.Outputs.AlbDnsName

Outputs:
  RootDomainName:
    Value: !Ref RootDomainName
  ApiDomainName:
    Value: !Ref ApiDomainName
  CloudFrontDomain:
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDomain
  BackendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.BackendEcrRepoUri
  FrontendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.FrontendEcrRepoUri
