AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Root Nested Stack (Enterprise Production-Ready, Packaged + Ordered)

Parameters:
  Env:
    Type: String
    AllowedValues: [dev, prod]
    Default: dev

  AppName:
    Type: String
    Default: fusionems-quantum

  RootDomainName:
    Type: String
    Default: app.fusionemsquantum.com

  ApiDomainName:
    Type: String
    Default: api.fusionemsquantum.com

  HostedZoneId:
    Type: String
    Description: Route53 Hosted Zone ID
    Default: Z0858801IZXAHSWCPH85

  ImageTagFrontend:
    Type: String

  ImageTagBackend:
    Type: String

  DesiredCount:
    Type: Number
    Default: 2

  DbInstanceClass:
    Type: String
    Default: db.t4g.medium

  DbMultiAZ:
    Type: String
    Default: 'false'
    AllowedValues: ['true', 'false']

  RedisNodeType:
    Type: String
    Default: cache.t4g.small

  AlertEmail:
    Type: String
    Default: founder@fusionemsquantum.com

  NestedTemplatesBucket:
    Type: String
    Description: S3 bucket where packaged nested templates are stored

  GraphTenantId:
    Type: String
    Default: ''

  GraphClientId:
    Type: String
    Default: ''

  GraphClientSecret:
    Type: String
    NoEcho: true
    Default: ''

  GraphFounderEmail:
    Type: String
    Default: ''

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:

  # ────────────────────────────────────────────────────────────────────────────
  # ACM (us-east-1 for CloudFront)
  # ────────────────────────────────────────────────────────────────────────────

  AcmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/acm.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
        HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # ────────────────────────────────────────────────────────────────────────────
  # Network
  # ────────────────────────────────────────────────────────────────────────────

  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/network.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # ────────────────────────────────────────────────────────────────────────────
  # Data (RDS + Redis + Secrets)
  # ────────────────────────────────────────────────────────────────────────────

  DataStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/data.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        DbInstanceClass: !Ref DbInstanceClass
        DbMultiAZ: !Ref DbMultiAZ
        RedisNodeType: !Ref RedisNodeType
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        GraphTenantId: !Ref GraphTenantId
        GraphClientId: !Ref GraphClientId
        GraphClientSecret: !Ref GraphClientSecret
        GraphFounderEmail: !Ref GraphFounderEmail
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # ────────────────────────────────────────────────────────────────────────────
  # Cognito
  # ────────────────────────────────────────────────────────────────────────────

  CognitoStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/cognito.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # ────────────────────────────────────────────────────────────────────────────
  # S3 Buckets
  # ────────────────────────────────────────────────────────────────────────────

  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/s3.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
      Tags:
        - Key: Environment
          Value: !Ref Env

  # ────────────────────────────────────────────────────────────────────────────
  # WAF
  # ────────────────────────────────────────────────────────────────────────────

  WafStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/waf.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
      Tags:
        - Key: Environment
          Value: !Ref Env

  # ────────────────────────────────────────────────────────────────────────────
  # Billing / Queues
  # ────────────────────────────────────────────────────────────────────────────

  BillingStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DataStack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/billing.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        AppSecretsArn: !GetAtt DataStack.Outputs.AppSecretsArn
        LambdaSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        LambdaSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        LambdaCodeS3Bucket: !Ref NestedTemplatesBucket
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # ────────────────────────────────────────────────────────────────────────────
  # Compute (ECS + ALB)
  # ────────────────────────────────────────────────────────────────────────────

  ComputeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - DataStack
      - CognitoStack
      - WafStack
      - BillingStack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/compute.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnets: !GetAtt NetworkStack.Outputs.PublicSubnets
        PrivateSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
        AlbSecurityGroupId: !GetAtt NetworkStack.Outputs.AlbSecurityGroupId
        EcsServiceSecurityGroupId: !GetAtt NetworkStack.Outputs.EcsServiceSecurityGroupId
        ImageTagFrontend: !Ref ImageTagFrontend
        ImageTagBackend: !Ref ImageTagBackend
        DesiredCount: !Ref DesiredCount
        DbSecretArn: !GetAtt DataStack.Outputs.DbSecretArn
        AppSecretsArn: !GetAtt DataStack.Outputs.AppSecretsArn
        RedisPrimaryEndpoint: !GetAtt DataStack.Outputs.RedisPrimaryEndpoint
        CognitoUserPoolId: !GetAtt CognitoStack.Outputs.UserPoolId
        CognitoClientId: !GetAtt CognitoStack.Outputs.UserPoolClientId
        AcmCertificateArn: !GetAtt AcmStack.Outputs.CertificateArn
        FaxClassifyQueueUrl: !GetAtt BillingStack.Outputs.FaxClassifyQueueUrl
        FaxMatchQueueUrl: !GetAtt BillingStack.Outputs.FaxMatchQueueUrl
        SupportAIQueueUrl: !GetAtt BillingStack.Outputs.SupportAIQueueUrl
        EdiGenerateQueueUrl: !GetAtt BillingStack.Outputs.EdiGenerateQueueUrl
        PdfDocKitQueueUrl: !GetAtt BillingStack.Outputs.PdfDocKitQueueUrl
        PdfClaimPacketQueueUrl: !GetAtt BillingStack.Outputs.PdfClaimPacketQueueUrl
        LegalPdfQueueUrl: !GetAtt BillingStack.Outputs.LegalPdfQueueUrl
        NERISPackImportQueueUrl: !GetAtt BillingStack.Outputs.NERISPackImportQueueUrl
        NERISPackCompileQueueUrl: !GetAtt BillingStack.Outputs.NERISPackCompileQueueUrl
        NERISExportQueueUrl: !GetAtt BillingStack.Outputs.NERISExportQueueUrl
        S3BucketDocs: !GetAtt S3Stack.Outputs.DocsBucketName
        S3BucketExports: !GetAtt S3Stack.Outputs.ExportsBucketName
        GraphTenantId: !Ref GraphTenantId
        GraphClientId: !Ref GraphClientId
        GraphClientSecret: !Ref GraphClientSecret
        GraphFounderEmail: !Ref GraphFounderEmail
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # Associate WAF with ALB
  WafAlbAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn: ComputeStack
    Properties:
      ResourceArn: !GetAtt ComputeStack.Outputs.AlbArn
      WebACLArn: !GetAtt WafStack.Outputs.WebAclArn

  # ────────────────────────────────────────────────────────────────────────────
  # Edge (CloudFront + Route53)
  # ────────────────────────────────────────────────────────────────────────────

  EdgeStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ComputeStack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/edge.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
        HostedZoneId: !Ref HostedZoneId
        AcmCertificateArnUsEast1: !GetAtt AcmStack.Outputs.CertificateArn
        AlbDnsName: !GetAtt ComputeStack.Outputs.AlbDnsName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

  # ────────────────────────────────────────────────────────────────────────────
  # Observability
  # ────────────────────────────────────────────────────────────────────────────

  ObservabilityStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ComputeStack
      - DataStack
    Properties:
      TemplateURL: !Sub 'https://${NestedTemplatesBucket}.s3.${AWS::Region}.amazonaws.com/observability.yml'
      Parameters:
        Env: !Ref Env
        AppName: !Ref AppName
        AlertEmail: !Ref AlertEmail
        EcsClusterName: !GetAtt ComputeStack.Outputs.ClusterName
        BackendServiceName: !GetAtt ComputeStack.Outputs.BackendServiceName
        AlbFullName: !GetAtt ComputeStack.Outputs.AlbFullName
        BackendTargetGroupFullName: !GetAtt ComputeStack.Outputs.BackendTargetGroupFullName
        DbInstanceId: !GetAtt DataStack.Outputs.DbInstanceId
        RedisClusterId: !GetAtt DataStack.Outputs.RedisReplicationGroupId
        RootDomainName: !Ref RootDomainName
        ApiDomainName: !Ref ApiDomainName
      Tags:
        - Key: Environment
          Value: !Ref Env
        - Key: Application
          Value: !Ref AppName

Outputs:
  RootDomainName:
    Value: !Ref RootDomainName

  ApiDomainName:
    Value: !Ref ApiDomainName

  CloudFrontDomain:
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDomain

  CloudFrontDistributionId:
    Value: !GetAtt EdgeStack.Outputs.CloudFrontDistributionId

  AcmCertificateArn:
    Description: ACM certificate ARN (CloudFront)
    Value: !GetAtt AcmStack.Outputs.CertificateArn

  BackendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.BackendEcrRepoUri

  FrontendEcrRepoUri:
    Value: !GetAtt ComputeStack.Outputs.FrontendEcrRepoUri

  CognitoUserPoolId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolId

  CognitoUserPoolClientId:
    Value: !GetAtt CognitoStack.Outputs.UserPoolClientId

  AlertTopicArn:
    Value: !GetAtt ObservabilityStack.Outputs.AlertTopicArn
