AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - Microsoft Graph Email Stack (Enterprise Secure)

Parameters:
  AppName:
    Type: String
  Env:
    Type: String

  GraphTenantId:
    Type: String
  GraphClientId:
    Type: String
  GraphClientSecret:
    Type: String
    NoEcho: true
  GraphFounderEmail:
    Type: String

Resources:

  GraphEmailSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${AppName}/${Env}/graph-email'
      Description: Microsoft Graph credentials for Founder Dashboard email
      SecretString: !Sub |
        {
          "tenant_id": "${GraphTenantId}",
          "client_id": "${GraphClientId}",
          "client_secret": "${GraphClientSecret}",
          "founder_email": "${GraphFounderEmail}"
        }

  GraphEmailAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub '${AppName}-${Env}-GraphEmailAccess'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Ref GraphEmailSecret

Outputs:
  GraphEmailSecretArn:
    Value: !Ref GraphEmailSecret
    Export:
      Name: !Sub '${AppName}-${Env}-GraphEmailSecretArn'

  GraphEmailAccessPolicyArn:
    Value: !Ref GraphEmailAccessPolicy
    Export:
      Name: !Sub '${AppName}-${Env}-GraphEmailAccessPolicyArn'
