AWSTemplateFormatVersion: '2010-09-09'
Description: FusionEMS Quantum - WAF Stack (Deployment-Time Webhook IP Allowlisting)

Parameters:
  AppName:
    Type: String
  Env:
    Type: String

  StripeWebhookCidrs:
    Type: CommaDelimitedList
    Description: Comma-delimited list of Stripe webhook IPv4 CIDRs

  TelnyxWebhookCidrs:
    Type: CommaDelimitedList
    Description: Comma-delimited list of Telnyx webhook IPv4 CIDRs

Resources:

  ##############################################
  # IP SETS (Created at Deployment)
  ##############################################

  StripeWebhookIpSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub '${AppName}-${Env}-stripe-webhooks'
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref StripeWebhookCidrs

  TelnyxWebhookIpSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: !Sub '${AppName}-${Env}-telnyx-webhooks'
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses: !Ref TelnyxWebhookCidrs

  ##############################################
  # WEB ACL
  ##############################################

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${AppName}-${Env}-waf'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${AppName}-${Env}-waf'

      Rules:

        #########################################
        # Allow Stripe Webhooks
        #########################################

        - Name: AllowStripeWebhooks
          Priority: 1
          Action:
            Allow: {}
          Statement:
            AndStatement:
              Statements:
                - IPSetReferenceStatement:
                    Arn: !GetAtt StripeWebhookIpSet.Arn
                - ByteMatchStatement:
                    SearchString: /api/v1/webhooks
                    FieldToMatch:
                      UriPath: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                    PositionalConstraint: STARTS_WITH
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowStripeWebhooks

        #########################################
        # Allow Telnyx Webhooks
        #########################################

        - Name: AllowTelnyxWebhooks
          Priority: 2
          Action:
            Allow: {}
          Statement:
            AndStatement:
              Statements:
                - IPSetReferenceStatement:
                    Arn: !GetAtt TelnyxWebhookIpSet.Arn
                - ByteMatchStatement:
                    SearchString: /api/v1/webhooks
                    FieldToMatch:
                      UriPath: {}
                    TextTransformations:
                      - Priority: 0
                        Type: NONE
                    PositionalConstraint: STARTS_WITH
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AllowTelnyxWebhooks

        #########################################
        # Block All Other Webhook Traffic
        #########################################

        - Name: BlockNonAllowlistedWebhookTraffic
          Priority: 3
          Action:
            Block: {}
          Statement:
            ByteMatchStatement:
              SearchString: /api/v1/webhooks
              FieldToMatch:
                UriPath: {}
              TextTransformations:
                - Priority: 0
                  Type: NONE
              PositionalConstraint: STARTS_WITH
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockNonAllowlistedWebhookTraffic

        #########################################
        # AWS Managed Protections
        #########################################

        - Name: AWSManagedRulesCommonRuleSet
          Priority: 10
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSet

        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 11
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: KnownBadInputs

        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 12
          OverrideAction: { None: {} }
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLi

        #########################################
        # Global Rate Limit
        #########################################

        - Name: GlobalRateLimit
          Priority: 20
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              Limit: 1500
              AggregateKeyType: IP
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: GlobalRateLimit

Outputs:
  WebAclArn:
    Value: !GetAtt WebACL.Arn
    Export:
      Name: !Sub '${AppName}-${Env}-WebAclArn'

  WebAclId:
    Value: !Ref WebACL
