from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(slots=True)
class AppError(Exception):
    code: str
    message: str
    status_code: int
    details: dict[str, Any] | None = None

    def to_response(self, trace_id: str | None) -> dict[str, Any]:
        return {
            "error": {
                "code": self.code,
                "message": self.message,
                "details": self.details or {},
                "trace_id": trace_id,
            }
        }


class ErrorCodes:
    INCIDENT_NOT_FOUND = "INCIDENT_NOT_FOUND"
    INCIDENT_CONFLICT = "INCIDENT_CONFLICT"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    INCIDENT_NUMBER_CONFLICT = "INCIDENT_NUMBER_CONFLICT"
    INCIDENT_INVALID_TRANSITION = "INCIDENT_INVALID_TRANSITION"
    INCIDENT_FORBIDDEN_TRANSITION = "INCIDENT_FORBIDDEN_TRANSITION"
    TENANT_SCOPE_REQUIRED = "TENANT_SCOPE_REQUIRED"
    PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND"
    PATIENT_CONFLICT = "PATIENT_CONFLICT"
    PATIENT_INCIDENT_MISMATCH = "PATIENT_INCIDENT_MISMATCH"
    VITAL_NOT_FOUND = "VITAL_NOT_FOUND"
    VITAL_CONFLICT = "VITAL_CONFLICT"
    VITAL_INCIDENT_MISMATCH = "VITAL_INCIDENT_MISMATCH"
    VITAL_PATIENT_MISMATCH = "VITAL_PATIENT_MISMATCH"
    INTEGRATION_NOT_FOUND = "INTEGRATION_NOT_FOUND"
    INTEGRATION_VERSION_REQUIRED = "INTEGRATION_VERSION_REQUIRED"
    IDEMPOTENCY_CONFLICT = "IDEMPOTENCY_CONFLICT"
    NARCOTIC_NEGATIVE_BALANCE = "NARCOTIC_NEGATIVE_BALANCE"
    NARCOTIC_WITNESS_REQUIRED = "NARCOTIC_WITNESS_REQUIRED"
    INVENTORY_NOT_FOUND = "INVENTORY_NOT_FOUND"
    MAINTENANCE_EVENT_NOT_FOUND = "MAINTENANCE_EVENT_NOT_FOUND"
    VEHICLE_NOT_FOUND = "VEHICLE_NOT_FOUND"
    FIRE_NERIS_REQUIRED_FIELDS_MISSING = "FIRE_NERIS_REQUIRED_FIELDS_MISSING"
    FIRE_INVALID_TRANSITION = "FIRE_INVALID_TRANSITION"
    FIRE_PROPERTY_NOT_FOUND = "FIRE_PROPERTY_NOT_FOUND"
    FIRE_INCIDENT_NOT_FOUND = "FIRE_INCIDENT_NOT_FOUND"

