from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(slots=True)
class AppError(Exception):
    code: str
    message: str
    status_code: int
    details: dict[str, Any] | None = None

    def to_response(self, trace_id: str | None) -> dict[str, Any]:
        return {
            "error": {
                "code": self.code,
                "message": self.message,
                "details": self.details or {},
                "trace_id": trace_id,
            }
        }


class ErrorCodes:
    INCIDENT_NOT_FOUND = "INCIDENT_NOT_FOUND"
    INCIDENT_CONFLICT = "INCIDENT_CONFLICT"
    CONCURRENCY_CONFLICT = "CONCURRENCY_CONFLICT"
    INCIDENT_NUMBER_CONFLICT = "INCIDENT_NUMBER_CONFLICT"
    INCIDENT_INVALID_TRANSITION = "INCIDENT_INVALID_TRANSITION"
    INCIDENT_FORBIDDEN_TRANSITION = "INCIDENT_FORBIDDEN_TRANSITION"
    TENANT_SCOPE_REQUIRED = "TENANT_SCOPE_REQUIRED"
    PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND"
    PATIENT_CONFLICT = "PATIENT_CONFLICT"
    PATIENT_INCIDENT_MISMATCH = "PATIENT_INCIDENT_MISMATCH"
    VITAL_NOT_FOUND = "VITAL_NOT_FOUND"
    VITAL_CONFLICT = "VITAL_CONFLICT"
    VITAL_INCIDENT_MISMATCH = "VITAL_INCIDENT_MISMATCH"
    VITAL_PATIENT_MISMATCH = "VITAL_PATIENT_MISMATCH"
    # CrewLink / Scheduling (Phase 6 & 7)
    CREW_MEMBER_NOT_FOUND = "CREW_MEMBER_NOT_FOUND"
    CREW_MEMBER_INACTIVE = "CREW_MEMBER_INACTIVE"
    CREW_MEMBER_FATIGUE_BLOCKED = "CREW_MEMBER_FATIGUE_BLOCKED"
    CREDENTIAL_MISSING_OR_EXPIRED = "CREDENTIAL_MISSING_OR_EXPIRED"
    KSS_SCORE_INVALID = "KSS_SCORE_INVALID"
    SHIFT_NOT_FOUND = "SHIFT_NOT_FOUND"
    SHIFT_INVALID_TIME_RANGE = "SHIFT_INVALID_TIME_RANGE"
    # CAD (Phase 9)
    CAD_INCIDENT_NOT_FOUND = "CAD_INCIDENT_NOT_FOUND"
    CAD_INCIDENT_CLOSED = "CAD_INCIDENT_CLOSED"
    CAD_INCIDENT_ALREADY_CLOSED = "CAD_INCIDENT_ALREADY_CLOSED"
    CAD_UNIT_STATUS_NOT_FOUND = "CAD_UNIT_STATUS_NOT_FOUND"
    # AI Layer (Phase 14)
    AI_SERVICE_UNAVAILABLE = "AI_SERVICE_UNAVAILABLE"
    AI_EMPTY_INCIDENT_DATA = "AI_EMPTY_INCIDENT_DATA"
    AI_GENERATION_FAILED = "AI_GENERATION_FAILED"
    AI_NARRATIVE_REJECTED = "AI_NARRATIVE_REJECTED"
    AI_NARRATIVE_INVALID_STATE = "AI_NARRATIVE_INVALID_STATE"
