"""AI narrative generation service for Phase 14 (Controlled & Self-Hosted AI Layer).

Provides a structured narrative generation wrapper enforcing:
- JSON-schema validated outputs via Pydantic.
- A mandatory ``review_state`` field so generated content never reaches the
  database without human review.
- Strict tenant-scoped audit trails via the event publisher.

The service delegates to the low-level AiService (OpenAI wrapper) but adds the
sovereign guardrails required for EMS/clinical documentation.
"""
from __future__ import annotations

import asyncio
import hashlib
import json
import logging
import uuid
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, field_validator

from core_app.core.errors import AppError

logger = logging.getLogger(__name__)


# ── Review state machine ──────────────────────────────────────────────────────

class NarrativeReviewState(StrEnum):
    PENDING_REVIEW = "pending_review"
    APPROVED = "approved"
    REJECTED = "rejected"


# ── Pydantic output schema ────────────────────────────────────────────────────

class NarrativeOutput(BaseModel):
    """Structured narrative generated by the AI layer.

    All fields are validated against this schema before being returned to the
    caller.  The ``review_state`` defaults to PENDING_REVIEW and must be
    explicitly set to APPROVED before the narrative is committed to the ePCR.
    """

    narrative_id: uuid.UUID = Field(default_factory=uuid.uuid4)
    tenant_id: uuid.UUID
    incident_id: uuid.UUID | None = None
    generated_text: str = Field(..., min_length=1, max_length=8192)
    prompt_hash: str = Field(
        ...,
        description="SHA-256 hex digest of the input prompt — enables deduplication.",
    )
    model_used: str
    usage_tokens: int = Field(ge=0)
    latency_ms: int = Field(ge=0)
    review_state: NarrativeReviewState = Field(
        default=NarrativeReviewState.PENDING_REVIEW,
        description=(
            "Generated narratives always start as PENDING_REVIEW. "
            "A clinician or supervisor must transition to APPROVED before "
            "the text is committed to the ePCR record."
        ),
    )
    reviewed_by: uuid.UUID | None = Field(
        default=None,
        description="UUID of the user who approved or rejected the narrative.",
    )
    reviewed_at: datetime | None = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    extra_metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("generated_text")
    @classmethod
    def _no_raw_pii_markers(cls, v: str) -> str:
        # Basic sanity guard: reject if the text appears to be raw JSON (model
        # escaped output) or contains obvious injection markers.
        stripped = v.strip()
        if stripped.startswith("{") and stripped.endswith("}"):
            try:
                json.loads(stripped)
                raise ValueError(
                    "generated_text appears to be raw JSON — the model output was not "
                    "correctly extracted.  Inspect the prompt template."
                )
            except (json.JSONDecodeError, ValueError) as exc:
                if "raw JSON" in str(exc):
                    raise
        return v

    model_config = {"use_enum_values": True}


# ── Service ───────────────────────────────────────────────────────────────────

class AIService:
    """Structured narrative generation wrapper for the FusionEMS AI layer.

    This service is intentionally kept thin:
    - It delegates LLM calls to the low-level :class:`~core_app.ai.service.AiService`.
    - It wraps every response in a :class:`NarrativeOutput` Pydantic schema.
    - It never writes to the database; callers receive a ``NarrativeOutput``
      with ``review_state=PENDING_REVIEW`` and are responsible for persisting
      after human approval.
    - All generation events are published to the event bus for audit purposes.
    """

    # Prompt templates – customise per use-case
    _SYSTEM_PROMPT = (
        "You are a highly trained EMS documentation specialist. "
        "Generate a concise, accurate, HIPAA-compliant patient care narrative "
        "based on the provided incident data. "
        "Use objective, third-person clinical language. "
        "Do not invent clinical findings not present in the input data. "
        "Output only the narrative text — no JSON, no markdown, no commentary."
    )

    def __init__(self, publisher: Any) -> None:
        self.publisher = publisher

    def _get_llm(self) -> Any:
        """Lazy-import and instantiate the low-level AiService to avoid hard
        dependency at module load time (allows the module to be imported in
        environments where OpenAI credentials are not configured).
        """
        try:
            from core_app.ai.service import AiService as _AiSvc  # noqa: PLC0415

            return _AiSvc()
        except Exception as exc:
            raise AppError(
                code="AI_SERVICE_UNAVAILABLE",
                message="AI service is not configured or unavailable.",
                status_code=503,
                details={"error": str(exc)},
            ) from exc

    async def generate_narrative(
        self,
        *,
        tenant_id: uuid.UUID,
        actor_user_id: uuid.UUID,
        incident_id: uuid.UUID | None = None,
        incident_data: dict[str, Any],
        max_tokens: int = 512,
        correlation_id: str | None = None,
    ) -> NarrativeOutput:
        """Generate a clinical narrative for an EMS incident.

        The output is returned with ``review_state=PENDING_REVIEW``.  The
        caller **must not** persist the generated text until a supervisor has
        transitioned the review_state to APPROVED via :meth:`approve_narrative`.

        Args:
            tenant_id: Tenant UUID for zero-trust isolation and audit.
            actor_user_id: UUID of the user initiating generation.
            incident_id: Optional ePCR incident UUID for cross-referencing.
            incident_data: Dict of clinical fields to include in the prompt.
                Must not be empty.
            max_tokens: Maximum token budget for the completion.
            correlation_id: Optional trace ID for observability.

        Returns:
            NarrativeOutput with review_state=PENDING_REVIEW.
        """
        if not incident_data:
            raise AppError(
                code="AI_EMPTY_INCIDENT_DATA",
                message="incident_data must not be empty.",
                status_code=422,
                details={},
            )

        user_prompt = self._build_user_prompt(incident_data)
        prompt_hash = hashlib.sha256(user_prompt.encode("utf-8")).hexdigest()

        llm = self._get_llm()
        try:
            generated_text, meta = await asyncio.to_thread(
                llm.chat,
                system=self._SYSTEM_PROMPT,
                user=user_prompt,
                max_tokens=max_tokens,
            )
        except Exception as exc:
            logger.error(
                "ai_service.generate_narrative_failed tenant_id=%s incident_id=%s error=%s",
                tenant_id,
                incident_id,
                exc,
                exc_info=exc,
            )
            raise AppError(
                code="AI_GENERATION_FAILED",
                message="Narrative generation failed.",
                status_code=502,
                details={"error": str(exc)},
            ) from exc

        output = NarrativeOutput(
            tenant_id=tenant_id,
            incident_id=incident_id,
            generated_text=generated_text.strip(),
            prompt_hash=prompt_hash,
            model_used=meta.get("model", "unknown"),
            usage_tokens=meta.get("usage", {}).get("total_tokens", 0),
            latency_ms=meta.get("latency_ms", 0),
            review_state=NarrativeReviewState.PENDING_REVIEW,
            extra_metadata={
                "actor_user_id": str(actor_user_id),
                "correlation_id": correlation_id,
            },
        )

        await self.publisher.publish(
            "ai.narrative_generated",
            tenant_id,
            output.narrative_id,
            {
                "incident_id": str(incident_id) if incident_id else None,
                "actor_user_id": str(actor_user_id),
                "model_used": output.model_used,
                "usage_tokens": output.usage_tokens,
                "latency_ms": output.latency_ms,
                "review_state": output.review_state,
            },
            entity_type="narrative",
            correlation_id=correlation_id,
        )

        logger.info(
            "ai_service.narrative_generated narrative_id=%s tenant_id=%s tokens=%d",
            output.narrative_id,
            tenant_id,
            output.usage_tokens,
        )
        return output

    def approve_narrative(
        self,
        *,
        output: NarrativeOutput,
        reviewer_id: uuid.UUID,
    ) -> NarrativeOutput:
        """Transition a narrative from PENDING_REVIEW to APPROVED.

        Does NOT persist anything — the caller is responsible for saving the
        returned object to the ePCR record after calling this method.

        Args:
            output: The NarrativeOutput previously returned by generate_narrative.
            reviewer_id: UUID of the approving clinician or supervisor.

        Returns:
            Updated NarrativeOutput with review_state=APPROVED.
        """
        if output.review_state == NarrativeReviewState.APPROVED:
            return output
        if output.review_state == NarrativeReviewState.REJECTED:
            raise AppError(
                code="AI_NARRATIVE_REJECTED",
                message="Cannot approve a previously rejected narrative.",
                status_code=422,
                details={"narrative_id": str(output.narrative_id)},
            )
        return output.model_copy(
            update={
                "review_state": NarrativeReviewState.APPROVED,
                "reviewed_by": reviewer_id,
                "reviewed_at": datetime.now(UTC),
            }
        )

    def reject_narrative(
        self,
        *,
        output: NarrativeOutput,
        reviewer_id: uuid.UUID,
    ) -> NarrativeOutput:
        """Transition a narrative from PENDING_REVIEW to REJECTED.

        Args:
            output: The NarrativeOutput previously returned by generate_narrative.
            reviewer_id: UUID of the rejecting clinician or supervisor.

        Returns:
            Updated NarrativeOutput with review_state=REJECTED.
        """
        if output.review_state != NarrativeReviewState.PENDING_REVIEW:
            raise AppError(
                code="AI_NARRATIVE_INVALID_STATE",
                message=(
                    f"Cannot reject a narrative with state '{output.review_state}'. "
                    "Only PENDING_REVIEW narratives can be rejected."
                ),
                status_code=422,
                details={
                    "narrative_id": str(output.narrative_id),
                    "current_state": output.review_state,
                },
            )
        return output.model_copy(
            update={
                "review_state": NarrativeReviewState.REJECTED,
                "reviewed_by": reviewer_id,
                "reviewed_at": datetime.now(UTC),
            }
        )

    # ── Prompt builder ────────────────────────────────────────────────────────

    @staticmethod
    def _build_user_prompt(incident_data: dict[str, Any]) -> str:
        """Render incident data as a structured text prompt for the LLM."""
        lines: list[str] = ["Incident Data:"]
        for key, value in incident_data.items():
            if value is not None and value != "":
                lines.append(f"  {key}: {value}")
        lines.append("\nGenerate the patient care narrative:")
        return "\n".join(lines)
